Algoritmo "imparPar"
// Descrição   : Verificar se um número é impar ou par
// Autor(a)    : João Victor da Silva Jardim
// Data atual  : 06/04/2024
Var
// Seção de Declarações das variáveis 
num:inteiro

Inicio
//entrada
ESCREVA("Digite um número inteiro")
LEIA(num)

//processamento
se (num mod 2 = 0) entao
      ESCREVA("O número", num, " é par!") //saida
senao
      ESCREVA("O número", num, " é impar!") //saida
fimse



Fimalgoritmo